server:
  port: 8888
spring:
  application:
    profiles:
        active: local
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
  http:
     encoding.charset: UTF-8  
     encoding.enable: true  
     encoding.force: true  
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8
      name:
      username: root
      password: 123456

custom:
  datasource:
    names: ds1,ds2
    ds1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8
      name:
      username: root
      password: 123456
    ds2:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://127.0.0.1:1433;databaseName=demo;
      name:
      username: sa
      password: 123456
logging:
  config:
    classpath: /config/logback/logback-stage.xml
#security:
#    oauth2:
#        client:
#            access-token-uri: http://localhost:8888/oauth/token
#            client-id: client_id
#            client-secret: client_secret
#            client-authentication-scheme: form
#            grant-type: client_credentials
#        resource:
#            user-info-uri: http://localhost:8888/check_token
