server:
  port: 8089
spring:
  application:
    name: staging
    profiles:
        active: local
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
  session:
      store-type: none
schedule:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
liquibase:
  change-log:
    classpath:/liquibase/master.xml
#logging:
#  config:
#    classpath: /config/logback/logback-stage.xml
